Update Readme with latest stable Electron version that does not raise exception
Currently on macOS if users follow the Readme and install Electron version 1.3.13 they may encounter the following error when they run `electron`, even when using say Node v6.6, Meteor v1.5, yarn v0.24.6,  gulp v3.9.1, OSX El Capitan 10.11.5 as I was. After making the following change I was able to run `electron` to open Mist successfully without any issues:

```
Error: ENOENT: no such file or directory, open '~/.config/yarn/global/node_modules/electron/path.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.<anonymous> (~/.config/yarn/global/node_modules/electron/index.js:4:42)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
```